# Generated by Django 3.2.9 on 2021-11-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibasic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('roll_no', models.IntegerField()),
            ],
        ),
    ]
