# Generated by Django 3.2.9 on 2021-11-30 06:40

from django.db import migrations, models
import django.utils.timezone
import uplode_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('uplode_api', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='profile',
        #     name='file',
        #     field=models.FileField(default=django.utils.timezone.now, upload_to=uplode_api.models.profile.nameFile),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(upload_to=uplode_api.models.profile),
        ),
    ]
