# Generated by Django 3.2.9 on 2021-11-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uplode_api', '0002_auto_20211130_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='file',
        ),
    ]
