# Generated by Django 3.2.9 on 2021-12-01 11:41

import django.core.validators
from django.db import migrations, models
import uplode_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('uplode_api', '0005_auto_20211130_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=uplode_api.models.path_and_rename, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), uplode_api.models.image_size]),
        ),
    ]
