# Generated by Django 3.2.9 on 2021-12-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailApi', '0002_alter_emailapi_attechment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('massage', models.CharField(max_length=100)),
            ],
        ),
    ]
