# Generated by Django 4.0.1 on 2022-01-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_to',
            field=models.DateField(),
        ),
    ]
